### ISSUE TITLE
Can we use this in a non-async environment?

### ISSUE THREAD

**Issue by EverlastingBugstopper** [jesusprubio/online#14]
It seems to me that having this crate be async may be a bit heavyweight, especially if someone is just trying to check if a user is online (no cross-thread communication is really necessary for most use cases i'd imagine). 

`reqwest` handles this by having a `blocking` module that mirrors the top-level async API but without requiring an async runtime.

Would love thoughts on this!

**Comment by jesusprubio** [comment]
Totally agree. Thanks, sorry for the late response.

Would you like to send a PR? If not I will try to do it asap.

**Comment by jesusprubio** [comment]
Working on it, let me a couple of days.

**Comment by jesusprubio** [comment]
Done:

- https://github.com/jesusprubio/online#synchronous
- https://github.com/jesusprubio/online/blob/master/examples/sync.rs

Please notice the new major (again, sorry).

**Comment by EverlastingBugstopper** [comment]
Amazing!! Thank you so much 😄
