### ISSUE TITLE
online function should take Option<Duration> instead of Option<u64>

### ISSUE THREAD

**Issue by Shadlock0133** [jesusprubio/online#3]
Signature of online doesn't indicate in what timescale timeout is. One has to read documentation.

Duration better communicates fact that the argument is a timeout, and in what timescale is operates in. Stdlib had sleep_ms & park_timeout function. They were deprecated in favour of sleep & park_timeout that take Duration as argument. Mirroring this would make for less confusion.

**Comment by Vurich** [comment]
Also if you take `impl Into<Option<Duration>>`, you can take `Duration` or `None`, which looks a lot nicer (essentially, `Some` becomes implicit)

**Comment by jesusprubio** [comment]
Thank you for the feedback. What a nice community! :smile_cat:. It's my first crate and I come from Node.js, so strings seemed easier at first. But you're right, I'm going to change it.

**Comment by jesusprubio** [comment]
Changed, thank you! :)
