### ISSUE TITLE
your current dependency simple_error is yanked

### ISSUE THREAD

**Issue by hskang9** [jesusprubio/online#9]
**Describe the bug**
Your dependency crate `simple_error` v0.1.13 is yanked, so it cannot be built.

**To Reproduce**

1. write `online = "0.2.0" `in `Cargo.toml`.
2. run `cargo build` 

change dependency crate `simple_error` to newest version and publish it.

**Comment by jesusprubio** [comment]
Done: https://github.com/jesusprubio/online/commit/d7ab07d996e79a05268d916f1f0773a0fb259dd1#diff-80398c5faae3c069e4e6aa2ed11b28c0L36
